### PR TITLE
All project major requirements. Please review and approve

### PR DESCRIPTION
**Pull request by treasure567**

### CODE REVIEW

**Review by ahmadinjo — APPROVED** [review]
There are conflicts with the stage branch, did pull the stage branch for your update or how did you do it?

**Comment by treasure567** [comment]
I think Its because of those bugs you fixed. I'll see if I can update mine 😩. I can't pull because it'll mess up my codes.

**Comment by ahmadinjo** [comment]
> I think Its because of those bugs you fixed. I'll see if I can update mine 😩. I can't pull because it'll mess up my codes.

I don't think so though. Check the pending reviews to see the conflicts. Only four files are conflicting

**Comment by ahmadinjo** [comment]
#32 Added multiple image upload features #32 should be merged before this

**Review by kelue — APPROVED** [review]
Alright, everything looks good except for the conflicts.

**Pull request merged**
